-- ���̺� ����
TRUNCATE TABLE RENTALS;
TRUNCATE TABLE NOTICES;
--TRUNCATE TABLE LOCKERS;
--TRUNCATE TABLE ACCOUNTS;

-- �� ���̺� IDENTITY ����(���� INSERT�� 1����)
ALTER TABLE RENTALS  MODIFY (ID  GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1));
ALTER TABLE NOTICES  MODIFY (ID  GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1));
--ALTER TABLE LOCKERS  MODIFY (ID  GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1));
--ALTER TABLE ACCOUNTS MODIFY (ID  GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1));

--------------------------------------

-- Admin ���� 3��
INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('admin01', 'Admin!1234', 'ADMIN', 'admin01@example.com', '010-1000-0001', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('admin02', 'Admin!1234', 'ADMIN', 'admin02@example.com', '010-1000-0002', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('admin03', 'Admin!1234', 'ADMIN', 'admin03@example.com', '010-1000-0003', 'Y');

-- �Ϲ� ���� 10��
INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user01', 'User!1234', 'USER', 'user01@example.com', '010-2000-0001', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user02', 'User!1234', 'USER', 'user02@example.com', '010-2000-0002', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user03', 'User!1234', 'USER', 'user03@example.com', '010-2000-0003', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user04', 'User!1234', 'USER', 'user04@example.com', '010-2000-0004', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user05', 'User!1234', 'USER', 'user05@example.com', '010-2000-0005', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user06', 'User!1234', 'USER', 'user06@example.com', '010-2000-0006', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user07', 'User!1234', 'USER', 'user07@example.com', '010-2000-0007', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user08', 'User!1234', 'USER', 'user08@example.com', '010-2000-0008', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user09', 'User!1234', 'USER', 'user09@example.com', '010-2000-0009', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user10', 'User!1234', 'USER', 'user10@example.com', '010-2000-0010', 'Y');

COMMIT;
select * from ACCOUNTS;

--------------------------------------

INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【重要】ロッカー定期点検のお知らせ', '安全確保のため、来週火曜 02:00–04:00 に定期点検を実施します。点検中は一部ロッカーがご利用いただけません。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【料金改定】一部サイズの料金変更', '運用コスト見直しのため、来月1日よりLサイズの料金を1日あたり100円値上げします。S/Mサイズは据え置きです。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【決済拡充】交通系IC対応エリア拡大', 'Suica/PASMO 等の交通系ICが、東口コンコースの全ロッカーでご利用可能になりました。現金も引き続き利用できます。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【大型】特大サイズロッカー増設', 'スーツケースXL対応の特大ロッカーを南改札外に12台増設しました。混雑時は係員にお声がけください。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【超過料金】深夜2時起点の課金について', '保管は1日単位で、午前2時を越えると翌日分の料金が加算されます。長時間ご利用の際はご注意ください。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【鍵紛失】対応と手数料', '鍵紛失時は身分証の提示と所定の書類記入が必要です。交換手数料として別途費用が発生します。管理カウンターまで。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【台風対応】安全確保のための一時休止', '荒天時は安全のため一部エリアを閉鎖する場合があります。最新情報は掲示および館内アナウンスをご確認ください。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【繁忙期】ゴールデンウィーク混雑予想', 'GW期間はロッカーの空きが少なくなります。できるだけ早めの確保と、サイズのご確認をおすすめします。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【臨時設置】夏祭り期間の臨時ロッカー', 'イベント期間中、中央口前に臨時ロッカーを設置します。台数に限りがありますので譲り合ってご利用ください。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【清掃】定期清掃・消毒の実施', '快適にご利用いただくため、毎日深夜にロッカー内外の清掃・消毒を行っています。清掃中は一時的に利用停止となります。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【停電点検】計画停電に伴う一時停止', '電気設備点検のため、来週木曜 01:30–03:30 は一部スマートロッカーの解錠が遅延する場合があります。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【返金対応】機器不具合時について', '機器不具合による重複課金等は現場確認のうえ返金いたします。レシートをお持ちのうえ管理カウンターまで。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【案内図】ロッカー位置マップ更新', '館内改装に伴いロッカー配置図を更新しました。サイズ別の位置は最新のフロアマップをご参照ください。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【予約】一部エリアで事前予約導入', '対象ロッカーで事前予約サービスの試行を開始しました。対象と利用方法は掲示のQRコードからご確認ください。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【持込禁止】危険物等の保管禁止', '可燃物・危険物・生もの・動物などの保管は禁止です。発見時は安全のため撤去・通報する場合があります。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【最長保管】保管制限と処理について', '保管は最長72時間までです。期限経過品は規約に基づき処理し、費用を請求する場合があります。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【問い合わせ】管理センター連絡先', 'お困りの際は管理センターまでご連絡ください。現場係員が不在の場合は掲示の電話番号へおかけください。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【防犯】カメラ作動中', '安全のためロッカー周辺は防犯カメラを常時作動しています。ご理解とご協力をお願いいたします。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【お願い】利用証明書・レシート保管', '返金・照会にはレシートや利用証明書が必要です。ご利用中は破棄せず大切に保管してください。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【迷子防止】ロッカー番号控えの推奨', 'ロッカー番号と設置場所を写真で控えてください。場所が思い出せない場合は係員にお申し出ください。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【サイズ】投入前のサイズ確認', '扉が閉まらない荷物は保管できません。無理な収納は故障や追加費用の原因となりますのでご注意ください。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【年末年始】営業時間の一部変更', '年末年始は一部エリアで短縮運用となります。営業時間は掲示または公式案内をご確認ください。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【IC決済】交通系ICの残高不足', '解錠時に残高不足の場合、差額精算が必要です。最寄りのチャージ機をご利用ください。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【QR解錠】一部機種での試験運用', 'QRコードによる解錠機能を一部で試験導入中です。対応ロッカーは表示ラベルをご確認ください。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【機器更新】決済端末の交換作業', '老朽化した決済端末の交換を順次行います。作業中は現金のみ、またはICのみの対応となる場合があります。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【サイズ表記】大型荷物の目安', '三辺合計が160cmを超える荷物は特大サイズをご利用ください。収まらない場合は手荷物預かりをご案内します。', 2);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【遺失物】忘れ物の取り扱い', '期限経過後の荷物や落とし物は所定の手続きを経て保管・処理します。お心当たりの方は管理センターへ。', 3);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【混雑回避】空き状況の確認', '混雑時間帯は空きが少なくなります。空き状況の目安は現地掲示と係員アナウンスをご参照ください。', 1);
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID) VALUES ('【マナー】長時間の占有ご遠慮', '必要最小限の時間でのご利用にご協力ください。長時間占有は他のお客様のご不便につながります。', 2);

COMMIT;
select * from NOTICES;

--------------------------------------

CREATE TABLE STG_LOCKERS (
  LOCATION  VARCHAR2(50),
  X         NUMBER(20,0),
  Y         NUMBER(20,0),
  CAPACITY  NUMBER(5,0)
);

select * from stg_lockers;

--------------------------------------
-- ����

-- �� �Ǽ� (����: 250)
SELECT COUNT(*) AS CNT FROM STG_LOCKERS;

-- ��ǥ �ߺ�(������ ���� �ʿ�)
SELECT LOCATION, X, Y, COUNT(*) 
FROM STG_LOCKERS 
GROUP BY LOCATION, X, Y 
HAVING COUNT(*) > 1;

-- capacity �� ���� Ȯ�� (1~4�� ���;� ��)
SELECT CAPACITY, COUNT(*) 
FROM STG_LOCKERS 
GROUP BY CAPACITY 
ORDER BY CAPACITY;

-- LOCATION ���� ����Ʈ ���� 50 �ʰ� ����(���� ������ ���̺� �÷� Ȯ�� �ʿ�)
SELECT * 
FROM STG_LOCKERS 
WHERE LENGTHB(LOCATION) > 50;

--------------------------------------

MERGE INTO LOCKERS t
USING (
  SELECT
    LOCATION,
    X,
    Y,
    CAPACITY,
    CASE CAPACITY
      WHEN 1 THEN 400
      WHEN 2 THEN 600
      WHEN 3 THEN 700
      ELSE 0
    END AS PRICE_CALC,
    CASE CAPACITY
      WHEN 4 THEN 5
      ELSE 1
    END AS STATUS_CALC
  FROM STG_LOCKERS
) s
ON (t.LOCATION = s.LOCATION AND t.X = s.X AND t.Y = s.Y)
WHEN MATCHED THEN
  UPDATE SET
    t.CAPACITY = s.CAPACITY,
    t.PRICE    = s.PRICE_CALC,
    t.STATUS   = s.STATUS_CALC
WHEN NOT MATCHED THEN
  INSERT (LOCATION, X, Y, CAPACITY, PRICE, STATUS)
  VALUES (s.LOCATION, s.X, s.Y, s.CAPACITY, s.PRICE_CALC, s.STATUS_CALC);


select * from lockers;

--------------------------------------

-- �� ���
SELECT COUNT(*) AS TOTAL FROM LOCKERS;

-- ���º� ���� (�� ����=5)
SELECT STATUS, COUNT(*) 
FROM LOCKERS 
GROUP BY STATUS 
ORDER BY STATUS;

-- ������/���� ���� ����
SELECT CAPACITY, PRICE, COUNT(*) 
FROM LOCKERS 
GROUP BY CAPACITY, PRICE 
ORDER BY CAPACITY, PRICE;

-- ��ǥ ���ϼ�(�ߺ� ������)
SELECT LOCATION, X, Y, COUNT(*) 
FROM LOCKERS 
GROUP BY LOCATION, X, Y 
HAVING COUNT(*) > 1;

--------------------------------------

-- ���� 5�� + ���� 5�� (�� ���� y=1..3: ��/��/��)
INSERT INTO LOCKERS (LOCATION, X, Y, CAPACITY, PRICE, STATUS)
SELECT '�ƫ󫸫�? 1ͭ' AS location,
       x,
       y,
       CASE y WHEN 1 THEN 3 WHEN 2 THEN 2 ELSE 1 END AS capacity,          -- 1=��,2=��,3=��
       CASE y WHEN 1 THEN 700 WHEN 2 THEN 500 ELSE 300 END AS price,        -- ��/��/�� ����
       CASE WHEN (x=3 AND y=2) OR (x=9 AND y=1) THEN 4 ELSE 1 END AS status -- 1=��� ����, 4=���� ��
FROM (SELECT LEVEL AS x FROM dual CONNECT BY LEVEL <= 11) xs
JOIN (SELECT LEVEL AS y FROM dual CONNECT BY LEVEL <= 3) ys ON 1=1
WHERE (x BETWEEN 1 AND 5 OR x BETWEEN 7 AND 11);
commit;

-- ��� 1�� (x=6, y=1..2: ��/��)
INSERT INTO LOCKERS (LOCATION, X, Y, CAPACITY, PRICE, STATUS)
SELECT '�ƫ󫸫�? 1ͭ', 6, y,
       CASE y WHEN 1 THEN 2 WHEN 2 THEN 1 END AS capacity,  -- y=1:��, y=2:��
       CASE y WHEN 1 THEN 500 WHEN 2 THEN 300 END AS price,
       1 AS status
FROM (SELECT 1 AS y FROM dual UNION ALL SELECT 2 FROM dual);

commit;
select * from LOCKERS;


ALTER TABLE LOCKERS ADD (LOCKER_CODE VARCHAR2(4));
ALTER TABLE LOCKERS ADD CONSTRAINT UQ_LOCKERS_LOCKER_CODE UNIQUE (LOCKER_CODE);
ALTER TABLE LOCKERS DROP CONSTRAINT UQ_LOCKERS_LOCKER_CODE;
ALTER TABLE LOCKERS DROP CONSTRAINT UQ_LOCKERS_LOCKER_CODE;
ALTER TABLE RENTALS DROP CONSTRAINT FK_RENTALS_LOCKER_CODE;

SELECT a.constraint_name, a.table_name, a.column_name
FROM user_cons_columns a
JOIN user_constraints c
  ON a.constraint_name = c.constraint_name
WHERE c.constraint_type = 'R'
  AND c.r_constraint_name = 'UQ_LOCKERS_LOCKER_CODE';

UPDATE LOCKERS l
SET LOCKER_CODE = (
  SELECT LPAD(
           TO_CHAR(
             6000
             + (
                 CASE t.location
                   WHEN '�����Ϣ��?Ѧ��'          THEN 0
                   WHEN '�����Ϣ?'                THEN 1
                   WHEN '��������Ϣ?'              THEN 2
                   WHEN '��Ϣ����Ϣ?5������Ϣ��'  THEN 3
                   WHEN '��Ϣ����Ϣ��Ϣ����'        THEN 4
                   WHEN '12������Ϣ��'             THEN 5
                   WHEN '����?��?�ӫ�����??'  THEN 6
                   ELSE 9
                 END
               ) * 100
             + t.rn
           ),
           4, '0'
         )
  FROM (
    SELECT
      id, location,
      ROW_NUMBER() OVER (
        PARTITION BY location
        ORDER BY x ASC, y ASC        
      ) AS rn
    FROM LOCKERS
    -- ��ĭ(status=5)�� �ڵ忡�� �����ϰ� �ʹٸ� WHERE status <> 5 �߰�
  ) t
  WHERE t.id = l.id
);



UPDATE LOCKERS l
SET LOCKER_CODE = (
  SELECT code_to_set
  FROM (
    SELECT id, location,
           ROW_NUMBER() OVER (PARTITION BY location ORDER BY x ASC, y ASC) AS rn
    FROM LOCKERS
  ) r
  JOIN (
    SELECT location, LOCKER_CODE AS code_to_set,
           ROW_NUMBER() OVER (PARTITION BY location ORDER BY LOCKER_CODE ASC) AS rn
    FROM LOCKERS
  ) c ON c.location = r.location AND c.rn = r.rn
  WHERE r.id = l.id
);
COMMIT;


COMMIT;

Select * from lockers;

--------------------------------------

INSERT INTO RENTALS (ID, USER_ID, LOCKER_CODE, START_TIME, END_TIME, STATUS)
SELECT "USER1"."ISEQ$$_112242".NEXTVAL, u, c, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '7' DAY, 2
FROM (
  SELECT 4 u,  6003 c FROM DUAL UNION ALL
  SELECT 5,    6008 FROM DUAL UNION ALL
  SELECT 6,    6014 FROM DUAL UNION ALL
  SELECT 7,    6021 FROM DUAL UNION ALL
  SELECT 8,    6039 FROM DUAL UNION ALL
  SELECT 9,    6045 FROM DUAL UNION ALL
  SELECT 10,   6103 FROM DUAL UNION ALL
  SELECT 11,   6109 FROM DUAL UNION ALL
  SELECT 12,   6114 FROM DUAL UNION ALL
  SELECT 13,   6202 FROM DUAL UNION ALL
  SELECT 4,    6207 FROM DUAL UNION ALL
  SELECT 5,    6216 FROM DUAL UNION ALL
  SELECT 6,    6223 FROM DUAL UNION ALL
  SELECT 7,    6235 FROM DUAL UNION ALL
  SELECT 8,    6242 FROM DUAL UNION ALL
  SELECT 9,    6250 FROM DUAL UNION ALL
  SELECT 10,   6257 FROM DUAL UNION ALL
  SELECT 11,   6259 FROM DUAL UNION ALL
  SELECT 12,   6260 FROM DUAL UNION ALL
  SELECT 13,   6261 FROM DUAL
);

UPDATE LOCKERS
SET STATUS = 3
WHERE LOCKER_CODE IN (
  6003,6008,6014,6021,6039,6045,6103,6109,6114,6202,
  6207,6216,6223,6235,6242,6250,6257,6259,6260,6261
);
COMMIT;

Select * from rentals;
Select * from accounts;