-- Å×ÀÌºí ºñ¿ì±â
TRUNCATE TABLE RENTALS;
TRUNCATE TABLE LOCKERS;
TRUNCATE TABLE NOTICES;
TRUNCATE TABLE ACCOUNTS;

-- °¢ Å×ÀÌºí IDENTITY ¸®¼Â(´ÙÀ½ INSERT°¡ 1ºÎÅÍ)
ALTER TABLE RENTALS  MODIFY (ID  GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1));
ALTER TABLE LOCKERS  MODIFY (ID  GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1));
ALTER TABLE NOTICES  MODIFY (ID  GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1));
ALTER TABLE ACCOUNTS MODIFY (ID  GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1));

--------------------------------------

-- Admin °èÁ¤ 3°³
INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('admin01', 'Admin!1234', 'ADMIN', 'admin01@example.com', '010-1000-0001', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('admin02', 'Admin!1234', 'ADMIN', 'admin02@example.com', '010-1000-0002', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('admin03', 'Admin!1234', 'ADMIN', 'admin03@example.com', '010-1000-0003', 'Y');

-- ÀÏ¹Ý À¯Àú 10°³
INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user01', 'User!1234', 'USER', 'user01@example.com', '010-2000-0001', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user02', 'User!1234', 'USER', 'user02@example.com', '010-2000-0002', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user03', 'User!1234', 'USER', 'user03@example.com', '010-2000-0003', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user04', 'User!1234', 'USER', 'user04@example.com', '010-2000-0004', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user05', 'User!1234', 'USER', 'user05@example.com', '010-2000-0005', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user06', 'User!1234', 'USER', 'user06@example.com', '010-2000-0006', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user07', 'User!1234', 'USER', 'user07@example.com', '010-2000-0007', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user08', 'User!1234', 'USER', 'user08@example.com', '010-2000-0008', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user09', 'User!1234', 'USER', 'user09@example.com', '010-2000-0009', 'Y');

INSERT INTO ACCOUNTS (USERNAME, PASSWORD, ROLE, EMAIL, PHONE_NUMBER, IS_ACTIVE)
VALUES ('user10', 'User!1234', 'USER', 'user10@example.com', '010-2000-0010', 'Y');

COMMIT;
select * from ACCOUNTS;

--------------------------------------

INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID)
VALUES ('«í«Ã««?ªÎ××éÄâ¢â÷', '«³«¤«óªò÷áìýª·¡¢ÝêªòøÍªáªÆËõªòªªö¢ªêª¯ªÀªµª¤¡£××éÄý­ªÏù±ªºËõªòÚ÷Ê¿ª·ªÆª¯ªÀªµª¤¡£', 1);

INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID)
VALUES ('ÓÞúþ«í«Ã««?ªÎÞÅéÄÛ°Ûö', 'ÓÞúþùÃÚªªò?Ò¡ª¹ªëð·ªÏ¡¢â¢îñª«ªé?ªØÐ³ÔõªËìýªì¡¢Ýêª¬ª·ªÃª«ªêøÍªÞªëª³ªÈªòü¬ìãª·ªÆª¯ªÀªµª¤¡£', 2);

INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID)
VALUES ('äÞ?Ûã?«í«Ã««?ðÃíÂ', 'Ûã?ªòàâïÒý­¡¢ù±ªºü¬ìã«Ü«¿«óªòäãª·ªÆª¯ªÀªµª¤¡£ØÎªìª¿íÞùêªÏÎ·×âìÑªËªªÙýª¤ùêªïª»ª¯ªÀªµª¤¡£', 3);

INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID)
VALUES ('××éÄãÁÊàªËªÄª¤ªÆ', '«í«Ã««?ªÎ××éÄªÏ24ãÁÊàÊ¦ÒöªÇª¹ª¬¡¢Ö§?××éÄªÏõÌÓÞ72ãÁÊàªÞªÇªÈªÊªêªÞª¹ªÎªÇª´ñ¼ëòª¯ªÀªµª¤¡£', 1);

INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID)
VALUES ('ËõªÎÝÑã÷ãÁªÎ??', 'ËõªòÝÑã÷ª·ª¿íÞùêªÏ¡¢ãóÝÂ?Ù¥ßöªòò¥?ªÎß¾¡¢Î·×âãøªÞªÇªªêÆª·ª¯ªÀªµª¤¡£î¢?ú¼ªËªÏâ¢?Öùª¬ª«ª«ªêªÞª¹¡£', 2);

COMMIT;
select * from NOTICES;

--------------------------------------

CREATE TABLE STG_LOCKERS (
  LOCATION  VARCHAR2(50),
  X         NUMBER(20,0),
  Y         NUMBER(20,0),
  CAPACITY  NUMBER(5,0)
);

select * from stg_lockers;

--------------------------------------
-- °ËÁõ

-- ÃÑ °Ç¼ö (¿¹»ó: 250)
SELECT COUNT(*) AS CNT FROM STG_LOCKERS;

-- ÁÂÇ¥ Áßº¹(ÀÖÀ¸¸é Á¤Á¦ ÇÊ¿ä)
SELECT LOCATION, X, Y, COUNT(*) 
FROM STG_LOCKERS 
GROUP BY LOCATION, X, Y 
HAVING COUNT(*) > 1;

-- capacity °ª ¹üÀ§ È®ÀÎ (1~4¸¸ ³ª¿Í¾ß ÇÔ)
SELECT CAPACITY, COUNT(*) 
FROM STG_LOCKERS 
GROUP BY CAPACITY 
ORDER BY CAPACITY;

-- LOCATION ±æÀÌ ¹ÙÀÌÆ® ±âÁØ 50 ÃÊ°ú ¿©ºÎ(¹®Á¦ ÀÖÀ¸¸é Å×ÀÌºí ÄÃ·³ È®Àå ÇÊ¿ä)
SELECT * 
FROM STG_LOCKERS 
WHERE LENGTHB(LOCATION) > 50;

--------------------------------------

MERGE INTO LOCKERS t
USING (
  SELECT
    LOCATION,
    X,
    Y,
    CAPACITY,
    CASE CAPACITY
      WHEN 1 THEN 400
      WHEN 2 THEN 600
      WHEN 3 THEN 700
      ELSE 0
    END AS PRICE_CALC,
    CASE CAPACITY
      WHEN 4 THEN 5
      ELSE 1
    END AS STATUS_CALC
  FROM STG_LOCKERS
) s
ON (t.LOCATION = s.LOCATION AND t.X = s.X AND t.Y = s.Y)
WHEN MATCHED THEN
  UPDATE SET
    t.CAPACITY = s.CAPACITY,
    t.PRICE    = s.PRICE_CALC,
    t.STATUS   = s.STATUS_CALC
WHEN NOT MATCHED THEN
  INSERT (LOCATION, X, Y, CAPACITY, PRICE, STATUS)
  VALUES (s.LOCATION, s.X, s.Y, s.CAPACITY, s.PRICE_CALC, s.STATUS_CALC);


select * from lockers;

--------------------------------------

-- ÃÑ Çà¼ö
SELECT COUNT(*) AS TOTAL FROM LOCKERS;

-- »óÅÂº° ºÐÆ÷ (ºó ½½·Ô=5)
SELECT STATUS, COUNT(*) 
FROM LOCKERS 
GROUP BY STATUS 
ORDER BY STATUS;

-- »çÀÌÁî/°¡°Ý ¸ÅÇÎ °ËÁõ
SELECT CAPACITY, PRICE, COUNT(*) 
FROM LOCKERS 
GROUP BY CAPACITY, PRICE 
ORDER BY CAPACITY, PRICE;

-- ÁÂÇ¥ À¯ÀÏ¼º(Áßº¹ ¾ø´ÂÁö)
SELECT LOCATION, X, Y, COUNT(*) 
FROM LOCKERS 
GROUP BY LOCATION, X, Y 
HAVING COUNT(*) > 1;

--------------------------------------

-- ÁÂÃø 5¿­ + ¿ìÃø 5¿­ (°¢ ¿­¿¡ y=1..3: ´ë/Áß/¼Ò)
INSERT INTO LOCKERS (LOCATION, X, Y, CAPACITY, PRICE, STATUS)
SELECT '«Æ«ó«¸«ó? 1Í­' AS location,
       x,
       y,
       CASE y WHEN 1 THEN 3 WHEN 2 THEN 2 ELSE 1 END AS capacity,          -- 1=¼Ò,2=Áß,3=´ë
       CASE y WHEN 1 THEN 700 WHEN 2 THEN 500 ELSE 300 END AS price,        -- ´ë/Áß/¼Ò °¡°Ý
       CASE WHEN (x=3 AND y=2) OR (x=9 AND y=1) THEN 4 ELSE 1 END AS status -- 1=»ç¿ë °¡´É, 4=Á¡°Ë Áß
FROM (SELECT LEVEL AS x FROM dual CONNECT BY LEVEL <= 11) xs
JOIN (SELECT LEVEL AS y FROM dual CONNECT BY LEVEL <= 3) ys ON 1=1
WHERE (x BETWEEN 1 AND 5 OR x BETWEEN 7 AND 11);
commit;

-- °¡¿îµ¥ 1¿­ (x=6, y=1..2: Áß/¼Ò)
INSERT INTO LOCKERS (LOCATION, X, Y, CAPACITY, PRICE, STATUS)
SELECT '«Æ«ó«¸«ó? 1Í­', 6, y,
       CASE y WHEN 1 THEN 2 WHEN 2 THEN 1 END AS capacity,  -- y=1:Áß, y=2:¼Ò
       CASE y WHEN 1 THEN 500 WHEN 2 THEN 300 END AS price,
       1 AS status
FROM (SELECT 1 AS y FROM dual UNION ALL SELECT 2 FROM dual);

commit;
select * from LOCKERS;


ALTER TABLE LOCKERS ADD (LOCKER_CODE VARCHAR2(4));
ALTER TABLE LOCKERS ADD CONSTRAINT UQ_LOCKERS_LOCKER_CODE UNIQUE (LOCKER_CODE);
ALTER TABLE LOCKERS DROP CONSTRAINT UQ_LOCKERS_LOCKER_CODE;
ALTER TABLE LOCKERS DROP CONSTRAINT UQ_LOCKERS_LOCKER_CODE;
ALTER TABLE RENTALS DROP CONSTRAINT FK_RENTALS_LOCKER_CODE;

SELECT a.constraint_name, a.table_name, a.column_name
FROM user_cons_columns a
JOIN user_constraints c
  ON a.constraint_name = c.constraint_name
WHERE c.constraint_type = 'R'
  AND c.r_constraint_name = 'UQ_LOCKERS_LOCKER_CODE';

UPDATE LOCKERS l
SET LOCKER_CODE = (
  SELECT LPAD(
           TO_CHAR(
             6000
             + (
                 CASE t.location
                   WHEN 'à¤ËÇóÎÏ¢Ïç?Ñ¦îñ'          THEN 0
                   WHEN 'à¤ËÇóÎÏ¢?'                THEN 1
                   WHEN 'ñéäçËÇóÎÏ¢?'              THEN 2
                   WHEN 'ÔÔÏ¢ËÇóÎÏ¢?5ÛãõóìýÏ¢îñ'  THEN 3
                   WHEN 'ÔÔÏ¢ËÇóÎÏ¢õóÏ¢ÜõÐÎ'        THEN 4
                   WHEN '12ÛãõóìýÏ¢îñ'             THEN 5
                   WHEN 'ªªËÔ?«µ?«Ó«¹«»«ó«¿??'  THEN 6
                   ELSE 9
                 END
               ) * 100
             + t.rn
           ),
           4, '0'
         )
  FROM (
    SELECT
      id, location,
      ROW_NUMBER() OVER (
        PARTITION BY location
        ORDER BY x ASC, y ASC        
      ) AS rn
    FROM LOCKERS
    -- ºóÄ­(status=5)À» ÄÚµå¿¡¼­ Á¦¿ÜÇÏ°í ½Í´Ù¸é WHERE status <> 5 Ãß°¡
  ) t
  WHERE t.id = l.id
);



UPDATE LOCKERS l
SET LOCKER_CODE = (
  SELECT code_to_set
  FROM (
    SELECT id, location,
           ROW_NUMBER() OVER (PARTITION BY location ORDER BY x ASC, y ASC) AS rn
    FROM LOCKERS
  ) r
  JOIN (
    SELECT location, LOCKER_CODE AS code_to_set,
           ROW_NUMBER() OVER (PARTITION BY location ORDER BY LOCKER_CODE ASC) AS rn
    FROM LOCKERS
  ) c ON c.location = r.location AND c.rn = r.rn
  WHERE r.id = l.id
);
COMMIT;


COMMIT;

Select * from lockers;

--------------------------------------

INSERT INTO RENTALS (ID, USER_ID, LOCKER_CODE, START_TIME, END_TIME, STATUS)
SELECT "USER1"."ISEQ$$_112242".NEXTVAL, u, c, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '7' DAY, 2
FROM (
  SELECT 4 u,  6003 c FROM DUAL UNION ALL
  SELECT 5,    6008 FROM DUAL UNION ALL
  SELECT 6,    6014 FROM DUAL UNION ALL
  SELECT 7,    6021 FROM DUAL UNION ALL
  SELECT 8,    6039 FROM DUAL UNION ALL
  SELECT 9,    6045 FROM DUAL UNION ALL
  SELECT 10,   6103 FROM DUAL UNION ALL
  SELECT 11,   6109 FROM DUAL UNION ALL
  SELECT 12,   6114 FROM DUAL UNION ALL
  SELECT 13,   6202 FROM DUAL UNION ALL
  SELECT 4,    6207 FROM DUAL UNION ALL
  SELECT 5,    6216 FROM DUAL UNION ALL
  SELECT 6,    6223 FROM DUAL UNION ALL
  SELECT 7,    6235 FROM DUAL UNION ALL
  SELECT 8,    6242 FROM DUAL UNION ALL
  SELECT 9,    6250 FROM DUAL UNION ALL
  SELECT 10,   6257 FROM DUAL UNION ALL
  SELECT 11,   6259 FROM DUAL UNION ALL
  SELECT 12,   6260 FROM DUAL UNION ALL
  SELECT 13,   6261 FROM DUAL
);

UPDATE LOCKERS
SET STATUS = 3
WHERE LOCKER_CODE IN (
  6003,6008,6014,6021,6039,6045,6103,6109,6114,6202,
  6207,6216,6223,6235,6242,6250,6257,6259,6260,6261
);
COMMIT;

Select * from rentals;
Select * from accounts;